// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0eZEZzg5cvjRagKIxLPowJ7SPZKswurM',
    appId: '1:8172956856:web:be1685880fd26537a1d84d',
    messagingSenderId: '8172956856',
    projectId: 'fir-panda-a687d',
    authDomain: 'fir-panda-a687d.firebaseapp.com',
    storageBucket: 'fir-panda-a687d.appspot.com',
    measurementId: 'G-4XNRZDS7Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEAK1Q5qfZZLVPu-1TRaP0KIRLCF73Jus',
    appId: '1:8172956856:android:1a5b16ec209504dea1d84d',
    messagingSenderId: '8172956856',
    projectId: 'fir-panda-a687d',
    storageBucket: 'fir-panda-a687d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSV6GEBRjDqykNTq1W6jppFLyU5hUDOyU',
    appId: '1:8172956856:ios:fae3dabe34c5c47da1d84d',
    messagingSenderId: '8172956856',
    projectId: 'fir-panda-a687d',
    storageBucket: 'fir-panda-a687d.appspot.com',
    iosClientId: '8172956856-vc1ha96h6ugpm52priim2oulq9lksfr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.panda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSV6GEBRjDqykNTq1W6jppFLyU5hUDOyU',
    appId: '1:8172956856:ios:fae3dabe34c5c47da1d84d',
    messagingSenderId: '8172956856',
    projectId: 'fir-panda-a687d',
    storageBucket: 'fir-panda-a687d.appspot.com',
    iosClientId: '8172956856-vc1ha96h6ugpm52priim2oulq9lksfr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.panda',
  );
}
